using Anvil.API;

namespace AmiaReforged.Classes.EffectUtils;

public class AmiaVfxTypes
{
    public const VfxType FnfFreezingSphere = (VfxType)2533;
    public const VfxType FnfVitriolicSphere = (VfxType)2534;
    public const VfxType ImpPulseColdChest = (VfxType)2535;
    public const VfxType ImpPulseFireChest = (VfxType)2536;
    public const VfxType ImpPulseAirChest = (VfxType)2537;
    public const VfxType ImpPulseEarthChest = (VfxType)2538;
    public const VfxType ImpPulseHolyChest = (VfxType)2539;
    public const VfxType ImpPulseNegativeChest = (VfxType)2540;
    public const VfxType ImpPulseOddChest = (VfxType)2551;
    public const VfxType ImpPulseMindChest = (VfxType)2560;
    public const VfxType ImpPulseShadowChest = (VfxType)2561;
    public const VfxType FnfDoomOdd = (VfxType)2552;
    public const VfxType FnfDoomMind = (VfxType)2553;
    public const VfxType FnfDoomSonic = (VfxType)2554;
    public const VfxType FnfDoomNegative = (VfxType)2555;
    public const VfxType FnfDoomCold = (VfxType)2556;
    public const VfxType FnfDoomAcid = (VfxType)2557;
    public const VfxType FnfDoomFire = (VfxType)2558;
    public const VfxType FnfDoomShadow = (VfxType)2559;
    public const VfxType FnfDoomHoly = (VfxType)2566;
    public const VfxType FnfDoomNature = (VfxType)2567;
    public const VfxType FnfDoomElectric = (VfxType)2568;
    public const VfxType ImpMirvNegative = (VfxType)2569;
    public const VfxType DurOrbRed = (VfxType)1036;
    public const VfxType DurOrbYellow = (VfxType)1039;
    public const VfxType FnfActionSurge = (VfxType)2514;
    public const VfxType FnfSecondWind = (VfxType)2515;
    public const VfxType FnfWhirlwind = (VfxType)2516;
    public const VfxType FnfDebilitate = (VfxType)2517;
    public const VfxType FnfSunder = (VfxType)2518;
    public const VfxType FnfIntensify = (VfxType)2519;
    public const VfxType FnfRally = (VfxType)2520;
    public const VfxType FnfBrace = (VfxType)2521;
    public const VfxType FnfBulwark = (VfxType)2522;
    public const VfxType FnfRetaliate = (VfxType)2523;
    public const VfxType DurMenace = (VfxType)2524;
    public const VfxType FnfImmobilize = (VfxType)2525;
    public const VfxType DurImmobilize = (VfxType)2526;
    public const VfxType FnfIndomitable = (VfxType)2527;
    public const VfxType FnfBardSong = (VfxType)2528;
    public const VfxType FnfCurseSong = (VfxType)2529;
    public const VfxType FnfMoonbeam = (VfxType)2530;
    public const VfxType SfxFnfBardSong = (VfxType)2531;
    public const VfxType SfxFnfCurseSong = (VfxType)2532;
    public const VfxType DurAuraGray9M = (VfxType)2541;
    public const VfxType DurTyrantFog = (VfxType)2542;
    public const VfxType DurDeathWardMid = (VfxType)2543;
    public const VfxType ImpMirvFire = (VfxType)2544;
    public const VfxType DurFireSwirl = (VfxType)2545;
    public const VfxType DurElectricShield = (VfxType)2546;
    public const VfxType ImpDruidClaw = (VfxType)2547;
    public const VfxType DurThornWall = (VfxType)2548;
    public const VfxType FnfThornSphere = (VfxType)2549;
    public const VfxType FnfSpringColor = (VfxType)2550;
    public const VfxType DurEvilSymbol = (VfxType)2562;
    public const VfxType DurPartyDust = (VfxType)2563;
    public const VfxType FnfPartyDust = (VfxType)2564;
    public const VfxType ImpFrog = (VfxType)2565;
    public const VfxType FnfLoudDecay = (VfxType)2133;
    public const VfxType FnfScreenShake2 = (VfxType)356;
    public const VfxType ImpQuillProjectile = (VfxType)359;
    public const VfxType ImpDestructLow = (VfxType)302;
}
