using System.Text;
using System.Text.Json;
namespace AmiaReforged.PwEngine.Features.Glyph.Nwn;

public sealed record GlyphNwnSnapshot(string ApiVersion, IReadOnlyList<GlyphNwnBindingCoverage> Bindings,
    IReadOnlyList<GlyphNwnConstantCoverage> Constants);

/// <summary>Offline upgrade audit. It compares generated compile-time metadata, never dispatches CLR members.</summary>
public static class GlyphNwnCoverage
{
    public static GlyphNwnSnapshot Current { get; } = new(GlyphNwnSurface.ApiVersion, GlyphNwnSurface.Bindings, GlyphNwnSurface.ConstantCoverage);
    public static JsonSerializerOptions JsonOptions { get; } = new() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase, PropertyNameCaseInsensitive = true, WriteIndented = true };
    public static string SnapshotJson() => JsonSerializer.Serialize(Current, JsonOptions) + "\n";
    public static IReadOnlyList<string> Compare(GlyphNwnSnapshot previous)
    {
        List<string> differences = [];
        if (previous.ApiVersion != Current.ApiVersion) differences.Add($"API version: {previous.ApiVersion} -> {Current.ApiVersion}");
        var oldMethods = previous.Bindings.GroupBy(m => m.Member).ToDictionary(g => g.Key, g => g.ToList(), StringComparer.Ordinal);
        var newMethods = Current.Bindings.GroupBy(m => m.Member).ToDictionary(g => g.Key, g => g.ToList(), StringComparer.Ordinal);
        foreach (string member in oldMethods.Keys.Concat(newMethods.Keys).Distinct().Order(StringComparer.Ordinal))
        {
            var old = oldMethods.GetValueOrDefault(member) ?? [];
            var current = newMethods.GetValueOrDefault(member) ?? [];
            // Match signatures first so a new overload does not hide an existing binding change.
            foreach (var method in current.ToArray())
            {
                var matching = old.FirstOrDefault(m => m.Signature == method.Signature);
                if (matching == null) continue;
                if (method != matching) Changed(matching, method);
                old.Remove(matching);
                current.Remove(method);
            }
            while (old.Count > 0 && current.Count > 0)
            {
                Changed(old[0], current[0]);
                old.RemoveAt(0);
                current.RemoveAt(0);
            }
            foreach (var method in current) differences.Add($"Added function: {method.Signature} [{method.Status}; review binding]");
            foreach (var method in old) differences.Add("Removed function: " + method.Signature);
        }
        void Changed(GlyphNwnBindingCoverage old, GlyphNwnBindingCoverage method) =>
            differences.Add($"Changed function: {old.Signature} -> {method.Signature} [{old.Status}/{old.Name} -> {method.Status}/{method.Name}; review binding]");
        var oldConstants = previous.Constants.ToDictionary(c => c.Member, StringComparer.Ordinal);
        var newConstants = Current.Constants.ToDictionary(c => c.Member, StringComparer.Ordinal);
        foreach (var constant in Current.Constants)
            if (!oldConstants.TryGetValue(constant.Member, out var old)) differences.Add($"Added constant: {constant.Member} = {constant.Value}");
            else if (constant != old) differences.Add($"Changed constant: {constant.Member}: {old.Type}/{old.Value}/{old.Name} -> {constant.Type}/{constant.Value}/{constant.Name}");
        foreach (var old in previous.Constants.Where(c => !newConstants.ContainsKey(c.Member))) differences.Add("Removed constant: " + old.Member);
        return differences;
    }
    public static string Report()
    {
        StringBuilder text = new("# NWScript binding coverage\n\nGenerated by Glyph.Docs. Do not edit.\n\nAPI: `" + GlyphNwnSurface.ApiVersion + "`\n\n");
        foreach (var group in Current.Bindings.GroupBy(b => b.Status).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            text.Append("## ").Append(group.Key).Append(" (").Append(group.Count()).Append(")\n\n");
            text.Append("| NWScript member | Glyph | Reason / signature |\n| --- | --- | --- |\n");
            foreach (var binding in group)
                text.Append("| `").Append(binding.Member).Append("` | ").Append(binding.Name).Append(" | ")
                    .Append((binding.Reason.Length == 0 ? binding.Signature : binding.Reason).Replace("|", "\\|").Replace("\n", " ")).Append(" |\n");
            text.Append('\n');
        }
        text.Append("## Constants\n\n").Append(GlyphNwnSurface.Constants.Count).Append(" published constants in ")
            .Append(GlyphNwnSurface.Constants.Select(c => c.Namespace).Distinct().Count()).Append(" domains; ")
            .Append(Current.Constants.Count - GlyphNwnSurface.Constants.Count).Append(" unselected constants.\n\n")
            .Append("The complete version, signatures, defaults, binding decisions, constant values and exclusions are in `NWN_API_SNAPSHOT.json`. ")
            .Append("Compare with `Glyph.Docs --compare-nwn <snapshot>` before updating the baseline.\n");
        return text.ToString();
    }
}
