using System.Globalization;
using System.Text;
using System.Text.Json;
using AmiaReforged.PwEngine.Features.Glyph.Language.Compilation;
using AmiaReforged.PwEngine.Features.Glyph.Language.Diagnostics;
using AmiaReforged.PwEngine.Features.Glyph.Language.Syntax;
namespace AmiaReforged.PwEngine.Features.Glyph.Nwn;

/// <summary>The prelude and its source-visible document are projections of one generated surface.</summary>
public static class GlyphStandardLibrary
{
    public static GlyphGlobalEnvironment Environment { get; } = Build();
    private static GlyphGlobalEnvironment Build()
    {
        SourceSpan span = new("Standard/global.glyph", 0, 0, 1, 1);
        var environment = GlyphGlobalEnvironment.FromDeclarations(GlyphNwnSurface.Constants.Select(c =>
            (GlyphDeclarationSyntax)new ConstantDeclarationSyntax(c.Name, new LiteralExpressionSyntax(c.Value, span), span)).ToArray(), out var errors);
        if (errors.Count > 0) throw new InvalidOperationException(string.Join("\n", errors));
        return environment;
    }

    public static string SourceDocument()
    {
        StringBuilder text = new("// Generated by Glyph.Docs from " + GlyphNwnSurface.ApiVersion + ". Do not edit.\n");
        foreach (var group in GlyphNwnSurface.Constants.GroupBy(c => c.Namespace).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            text.Append("\n// ").Append(group.Key).Append('\n');
            foreach (var constant in group)
            {
                string value = constant.Value is string s ? JsonSerializer.Serialize(s) : Convert.ToString(constant.Value, CultureInfo.InvariantCulture)!;
                text.Append("const ").Append(constant.Name).Append(": ").Append(constant.Type).Append(" = ").Append(value).Append('\n');
            }
        }
        return text.ToString();
    }
}
