using Anvil.API;

namespace AmiaReforged.PwEngine.Features.Chat.Commands.Legacy;

/// <summary>
/// Contains the list of buff spell IDs that should be removed by the debuff command.
/// Ported from GetIsNonMalignSpellEffect() in mod_pla_cmd.nss.
/// </summary>
public static class SpellBuffWhitelist
{
    private static readonly HashSet<int> BuffSpellIds = new()
    {
        (int)Spell.Aid,
        (int)Spell.Amplify,
        (int)Spell.AuraOfVitality,
        (int)Spell.Auraofglory,
        (int)Spell.Awaken,
        (int)Spell.Barkskin,
        (int)Spell.Battletide,
        (int)Spell.Blackstaff,
        (int)Spell.BladeThirst,
        (int)Spell.Bless,
        (int)Spell.BlessWeapon,
        (int)Spell.BloodFrenzy,
        (int)Spell.BullsStrength,
        (int)Spell.Camoflage,
        (int)Spell.CatsGrace,
        (int)Spell.ClairaudienceAndClairvoyance,
        (int)Spell.Clarity,
        (int)Spell.DeathArmor,
        (int)Spell.DeafeningClang,
        (int)Spell.Darkvision,
        (int)Spell.DeathWard,
        (int)Spell.Displacement,
        (int)Spell.DivineFavor,
        (int)Spell.DivineMight,
        (int)Spell.DivinePower,
        (int)Spell.DivineShield,
        (int)Spell.EagleSpledor,
        (int)Spell.ElementalShield,
        (int)Spell.Endurance,
        (int)Spell.EndureElements,
        (int)Spell.EnergyBuffer,
        (int)Spell.EntropicShield,
        (int)Spell.EpicMageArmor,
        (int)Spell.EtherealVisage,
        (int)Spell.Etherealness,
        (int)Spell.ExpeditiousRetreat,
        (int)Spell.FoxsCunning,
        (int)Spell.FreedomOfMovement,
        (int)Spell.GhostlyVisage,
        (int)Spell.GlobeOfInvulnerability,
        (int)Spell.GreaterBullsStrength,
        (int)Spell.GreaterCatsGrace,
        (int)Spell.GreaterEagleSplendor,
        (int)Spell.GreaterEndurance,
        (int)Spell.GreaterFoxsCunning,
        (int)Spell.GreaterMagicWeapon,
        (int)Spell.GreaterOwlsWisdom,
        (int)Spell.GreaterShadowConjurationMinorGlobe,
        (int)Spell.GreaterShadowConjurationMirrorImage,
        (int)Spell.GreaterSpellMantle,
        (int)Spell.GreaterStoneskin,
        (int)Spell.Haste,
        (int)Spell.HolyAura,
        (int)Spell.HolySword,
        (int)Spell.Identify,
        (int)Spell.ImprovedInvisibility,
        (int)Spell.Invisibility,
        (int)Spell.InvisibilityPurge,
        (int)Spell.InvisibilitySphere,
        (int)Spell.IounStoneBlue,
        (int)Spell.IounStoneDeepRed,
        (int)Spell.IounStoneDustyRose,
        (int)Spell.IounStonePaleBlue,
        (int)Spell.IounStonePink,
        (int)Spell.IounStonePinkGreen,
        (int)Spell.IounStoneScarletBlue,
        (int)Spell.Ironguts,
        (int)Spell.KeenEdge,
        (int)Spell.LegendLore,
        (int)Spell.LesserMindBlank,
        (int)Spell.LesserSpellMantle,
        (int)Spell.MageArmor,
        (int)Spell.MagicCircleAgainstChaos,
        (int)Spell.MagicCircleAgainstEvil,
        (int)Spell.MagicCircleAgainstGood,
        (int)Spell.MagicCircleAgainstLaw,
        (int)Spell.MagicWeapon,
        (int)Spell.MagicVestment,
        (int)Spell.MassCamoflage,
        (int)Spell.MassHaste,
        (int)Spell.MestilsAcidSheath,
        (int)Spell.MindBlank,
        (int)Spell.MinorGlobeOfInvulnerability,
        (int)Spell.MonstrousRegeneration,
        (int)Spell.NegativeEnergyProtection,
        (int)Spell.OneWithTheLand,
        (int)Spell.OwlsInsight,
        (int)Spell.OwlsWisdom,
        (int)Spell.Prayer,
        (int)Spell.Premonition,
        (int)Spell.ProtectionFromChaos,
        (int)Spell.ProtectionFromElements,
        (int)Spell.ProtectionFromEvil,
        (int)Spell.ProtectionFromGood,
        (int)Spell.ProtectionFromLaw,
        (int)Spell.ProtectionFromSpells,
        (int)Spell.Regenerate,
        (int)Spell.RemoveFear,
        (int)Spell.ResistElements,
        (int)Spell.Resistance,
        (int)Spell.Sanctuary,
        (int)Spell.SeeInvisibility,
        (int)Spell.ShadesStoneskin,
        (int)Spell.ShadowConjurationInivsibility,
        (int)Spell.ShadowConjurationMageArmor,
        (int)Spell.ShadowEvade,
        (int)Spell.ShadowShield,
        (int)Spell.Shield,
        (int)Spell.ShieldOfFaith,
        (int)Spell.ShieldOfLaw,
        (int)Spell.SpellMantle,
        (int)Spell.SpellResistance,
        (int)Spell.StoneBones,
        (int)Spell.Stoneskin,
        (int)Spell.TensersTransformation,
        (int)Spell.TrueSeeing,
        (int)Spell.TrueStrike,
        (int)Spell.TymorasSmile,
        (int)Spell.UndeathsEternalFoe,
        (int)Spell.VineMineCamouflage,
        (int)Spell.Virtue,
    };

    /// <summary>
    /// Returns true if the given spell ID is a buff that should be removed by the debuff command.
    /// </summary>
    public static bool IsBuffSpell(int spellId) => BuffSpellIds.Contains(spellId);
}
