using AmiaReforged.PwEngine.Features.WorldEngine.Subsystems.Codex.Domain.Entities;
using AmiaReforged.PwEngine.Features.WorldEngine.Subsystems.Codex.Domain.Enums;
using AmiaReforged.PwEngine.Features.WorldEngine.Subsystems.Codex.Domain.ValueObjects;

namespace AmiaReforged.PwEngine.Features.WorldEngine.Subsystems.Codex.Domain.Aggregates;

/// <summary>
/// Aggregate root representing a blueprint for dynamic quests.
/// Templates define the structure, rules, and constraints for quests that can be
/// posted to bounty boards, offered by NPCs, or generated by world events.
/// Postings (live, claimable instances) are created from templates via <see cref="CreatePosting"/>.
/// </summary>
public class DynamicQuestTemplate
{
    /// <summary>
    /// Unique identifier for this template.
    /// </summary>
    public TemplateId TemplateId { get; init; }

    /// <summary>
    /// Display title for quests created from this template.
    /// </summary>
    public required string Title { get; init; }

    /// <summary>
    /// Detailed description shown to adventurers when browsing available quests.
    /// </summary>
    public required string Description { get; init; }

    /// <summary>
    /// How this quest enters the world (bounty board, NPC, world event, etc.).
    /// </summary>
    public DynamicQuestSource Source { get; init; } = DynamicQuestSource.BountyBoard;

    /// <summary>
    /// Controls how many adventurers can simultaneously claim postings from this template.
    /// </summary>
    public ClaimMode ClaimMode { get; init; } = ClaimMode.Unlimited;

    /// <summary>
    /// Maximum number of simultaneous claimants per posting.
    /// Only meaningful when <see cref="ClaimMode"/> is <see cref="Enums.ClaimMode.Limited"/>.
    /// </summary>
    public int MaxClaimants { get; init; } = 1;

    /// <summary>
    /// Wall-clock duration from the moment a character claims the quest until it expires.
    /// Null means no time limit.
    /// </summary>
    public TimeSpan? TimeLimit { get; init; }

    /// <summary>
    /// What happens when the time limit elapses for a character's active quest.
    /// </summary>
    public ExpiryBehavior ExpiryBehavior { get; init; } = ExpiryBehavior.Fail;

    /// <summary>
    /// Maximum number of times a single character can complete this quest.
    /// 0 means unlimited completions.
    /// </summary>
    public int MaxCompletionsPerCharacter { get; init; }

    /// <summary>
    /// Cooldown period after completion before the same character can accept the quest again.
    /// Null means no cooldown (immediately re-acceptable, subject to <see cref="MaxCompletionsPerCharacter"/>).
    /// </summary>
    public TimeSpan? CooldownAfterCompletion { get; init; }

    /// <summary>
    /// Optional duration for postings created from this template.
    /// After this duration, the posting itself expires and is removed from boards/NPCs.
    /// Null means the posting stays available indefinitely (until manually removed or deactivated).
    /// </summary>
    public TimeSpan? PostingDuration { get; init; }

    /// <summary>
    /// Reward granted upon quest completion, in addition to any per-stage rewards.
    /// </summary>
    public RewardMix BaseReward { get; init; } = RewardMix.Empty;

    /// <summary>
    /// Ordered stages defining the quest structure. Reuses the existing <see cref="QuestStage"/> model.
    /// </summary>
    public List<QuestStage> StageTemplates { get; init; } = [];

    /// <summary>
    /// Keywords associated with this template for searching and filtering.
    /// </summary>
    public List<Keyword> Keywords { get; init; } = [];

    /// <summary>
    /// Whether this template is currently active and can produce new postings.
    /// DMs can deactivate templates to temporarily remove them from circulation.
    /// </summary>
    public bool IsActive { get; private set; } = true;

    /// <summary>
    /// When this template was created.
    /// </summary>
    public DateTime CreatedAt { get; init; }

    /// <summary>
    /// Creates a live, claimable posting from this template.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown if the template is not active.</exception>
    public DynamicQuestPosting CreatePosting(DateTime postedAt)
    {
        if (!IsActive)
            throw new InvalidOperationException($"Cannot create posting from inactive template {TemplateId}");

        DateTime? expiresAt = PostingDuration.HasValue
            ? postedAt + PostingDuration.Value
            : null;

        return new DynamicQuestPosting
        {
            PostingId = PostingId.NewId(),
            SourceTemplateId = TemplateId,
            Title = Title,
            Description = Description,
            PostedAt = postedAt,
            ExpiresAt = expiresAt,
            ClaimMode = ClaimMode,
            MaxClaimants = MaxClaimants,
            TimeLimit = TimeLimit,
            ExpiryBehavior = ExpiryBehavior,
            BaseReward = BaseReward,
            StageTemplates = StageTemplates,
            Keywords = Keywords
        };
    }

    /// <summary>
    /// Deactivates this template, preventing new postings from being created.
    /// </summary>
    public void Deactivate() => IsActive = false;

    /// <summary>
    /// Reactivates this template, allowing new postings to be created.
    /// </summary>
    public void Activate() => IsActive = true;

    /// <summary>
    /// Validates the template configuration. Returns null if valid,
    /// otherwise a human-readable error message.
    /// </summary>
    public string? Validate()
    {
        if (string.IsNullOrWhiteSpace(Title))
            return "Template title cannot be empty";

        if (string.IsNullOrWhiteSpace(Description))
            return "Template description cannot be empty";

        if (ClaimMode == ClaimMode.Limited && MaxClaimants < 1)
            return "MaxClaimants must be at least 1 when ClaimMode is Limited";

        if (ClaimMode == ClaimMode.Exclusive && MaxClaimants != 1)
            return "MaxClaimants must be 1 when ClaimMode is Exclusive";

        if (TimeLimit.HasValue && TimeLimit.Value <= TimeSpan.Zero)
            return "TimeLimit must be a positive duration";

        if (MaxCompletionsPerCharacter < 0)
            return "MaxCompletionsPerCharacter cannot be negative";

        if (CooldownAfterCompletion.HasValue && CooldownAfterCompletion.Value <= TimeSpan.Zero)
            return "CooldownAfterCompletion must be a positive duration";

        if (PostingDuration.HasValue && PostingDuration.Value <= TimeSpan.Zero)
            return "PostingDuration must be a positive duration";

        string? rewardError = BaseReward.Validate();
        if (rewardError != null)
            return $"BaseReward: {rewardError}";

        return null;
    }
}
