using System.Text.Json;
using System.Text.Json.Serialization;
using AmiaReforged.PwEngine.Features.WorldEngine.SharedKernel;
using AmiaReforged.PwEngine.Features.WorldEngine.SharedKernel.ValueObjects;
using AmiaReforged.PwEngine.Features.WorldEngine.Subsystems.Harvesting;
using AmiaReforged.PwEngine.Features.WorldEngine.Subsystems.Industries;
using AmiaReforged.PwEngine.Features.WorldEngine.Subsystems.Items.ItemData;
using Anvil;

namespace AmiaReforged.PwEngine.Features.WorldEngine.API.Controllers;

/// <summary>
/// REST API controller for managing recipe template definitions.
/// Supports CRUD operations and cache invalidation for the admin panel.
/// </summary>
public class RecipeTemplateController
{
    private static readonly JsonSerializerOptions ImportOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        Converters = { new JsonStringEnumConverter() }
    };

    /// <summary>
    /// List all recipe templates with optional search and pagination.
    /// GET /api/worldengine/recipe-templates?search=&amp;page=1&amp;pageSize=50
    /// </summary>
    [HttpGet("/api/worldengine/recipe-templates")]
    public static async Task<ApiResult> GetAll(RouteContext ctx)
    {
        IRecipeTemplateRepository repo = ResolveRepository();
        string? search = ctx.GetQueryParam("search");
        int page = int.TryParse(ctx.GetQueryParam("page"), out int p) ? Math.Max(1, p) : 1;
        int pageSize = int.TryParse(ctx.GetQueryParam("pageSize"), out int ps) ? Math.Clamp(ps, 1, 200) : 50;

        List<RecipeTemplate> paged = repo.Search(search, page, pageSize, out int totalCount);

        return await Task.FromResult(new ApiResult(200, new
        {
            items = paged.Select(ToDto),
            totalCount,
            page,
            pageSize
        }));
    }

    /// <summary>
    /// Get a single recipe template by tag.
    /// GET /api/worldengine/recipe-templates/{tag}
    /// </summary>
    [HttpGet("/api/worldengine/recipe-templates/{tag}")]
    public static async Task<ApiResult> GetByTag(RouteContext ctx)
    {
        string tag = ctx.GetRouteValue("tag");
        IRecipeTemplateRepository repo = ResolveRepository();

        RecipeTemplate? template = repo.GetByTag(tag);
        if (template == null)
        {
            return await Task.FromResult(new ApiResult(404, new ErrorResponse(
                "Not found", $"No recipe template with tag '{tag}'")));
        }

        return await Task.FromResult(new ApiResult(200, ToDto(template)));
    }

    /// <summary>
    /// Get all recipe templates for a specific industry.
    /// GET /api/worldengine/recipe-templates/industry/{industryTag}
    /// </summary>
    [HttpGet("/api/worldengine/recipe-templates/industry/{industryTag}")]
    public static async Task<ApiResult> GetByIndustry(RouteContext ctx)
    {
        string industryTag = ctx.GetRouteValue("industryTag");
        IRecipeTemplateRepository repo = ResolveRepository();

        List<RecipeTemplate> templates = repo.GetByIndustry(new IndustryTag(industryTag));

        return await Task.FromResult(new ApiResult(200, new
        {
            items = templates.Select(ToDto),
            totalCount = templates.Count
        }));
    }

    /// <summary>
    /// Get the expanded concrete recipes generated by a specific template.
    /// GET /api/worldengine/recipe-templates/{tag}/expanded
    /// </summary>
    [HttpGet("/api/worldengine/recipe-templates/{tag}/expanded")]
    public static async Task<ApiResult> GetExpanded(RouteContext ctx)
    {
        string tag = ctx.GetRouteValue("tag");
        RecipeTemplateExpander expander = ResolveExpander();

        List<Recipe> expandedRecipes = expander.GetExpandedRecipesForTemplate(tag);

        return await Task.FromResult(new ApiResult(200, new
        {
            templateTag = tag,
            recipes = expandedRecipes.Select(r => new
            {
                RecipeId = r.RecipeId.Value,
                r.Name,
                r.Description,
                IndustryTag = r.IndustryTag.Value,
                Ingredients = r.Ingredients.Select(i => new
                {
                    i.ItemTag,
                    Quantity = i.Quantity.Value,
                    i.MinQuality,
                    i.IsConsumed
                }),
                Products = r.Products.Select(p => new
                {
                    p.ItemTag,
                    Quantity = p.Quantity.Value,
                    p.SuccessChance
                })
            }),
            totalExpanded = expandedRecipes.Count
        }));
    }

    /// <summary>
    /// Create a new recipe template definition.
    /// POST /api/worldengine/recipe-templates
    /// </summary>
    [HttpPost("/api/worldengine/recipe-templates")]
    public static async Task<ApiResult> Create(RouteContext ctx)
    {
        RecipeTemplateDto? dto = await ctx.ReadJsonBodyAsync<RecipeTemplateDto>();
        if (dto == null)
        {
            return new ApiResult(400, new ErrorResponse("Bad request", "Request body is required"));
        }

        string? validationError = ValidateDto(dto);
        if (validationError != null)
        {
            return new ApiResult(400, new ErrorResponse("Validation failed", validationError));
        }

        IRecipeTemplateRepository repo = ResolveRepository();

        if (repo.GetByTag(dto.Tag) != null)
        {
            return new ApiResult(409, new ErrorResponse("Conflict",
                $"Recipe template with tag '{dto.Tag}' already exists"));
        }

        RecipeTemplate template = FromDto(dto);
        repo.Add(template);

        // Invalidate the template expansion cache
        InvalidateExpansionCache();

        return new ApiResult(201, ToDto(template));
    }

    /// <summary>
    /// Update an existing recipe template definition by tag.
    /// PUT /api/worldengine/recipe-templates/{tag}
    /// </summary>
    [HttpPut("/api/worldengine/recipe-templates/{tag}")]
    public static async Task<ApiResult> Update(RouteContext ctx)
    {
        string tag = ctx.GetRouteValue("tag");
        IRecipeTemplateRepository repo = ResolveRepository();

        RecipeTemplate? existing = repo.GetByTag(tag);
        if (existing == null)
        {
            return await Task.FromResult(new ApiResult(404, new ErrorResponse(
                "Not found", $"No recipe template with tag '{tag}'")));
        }

        RecipeTemplateDto? dto = await ctx.ReadJsonBodyAsync<RecipeTemplateDto>();
        if (dto == null)
        {
            return new ApiResult(400, new ErrorResponse("Bad request", "Request body is required"));
        }

        string? validationError = ValidateDto(dto);
        if (validationError != null)
        {
            return new ApiResult(400, new ErrorResponse("Validation failed", validationError));
        }

        dto = dto with { Tag = tag };
        RecipeTemplate template = FromDto(dto);
        repo.Update(template);

        InvalidateExpansionCache();

        return new ApiResult(200, ToDto(template));
    }

    /// <summary>
    /// Delete a recipe template definition by tag.
    /// DELETE /api/worldengine/recipe-templates/{tag}
    /// </summary>
    [HttpDelete("/api/worldengine/recipe-templates/{tag}")]
    public static async Task<ApiResult> Delete(RouteContext ctx)
    {
        string tag = ctx.GetRouteValue("tag");
        IRecipeTemplateRepository repo = ResolveRepository();

        bool deleted = repo.Delete(tag);
        if (!deleted)
        {
            return await Task.FromResult(new ApiResult(404, new ErrorResponse(
                "Not found", $"No recipe template with tag '{tag}'")));
        }

        InvalidateExpansionCache();

        return await Task.FromResult(new ApiResult(204, new { message = "Deleted" }));
    }

    /// <summary>
    /// Force re-expansion of all recipe templates.
    /// POST /api/worldengine/recipe-templates/invalidate
    /// </summary>
    [HttpPost("/api/worldengine/recipe-templates/invalidate")]
    public static async Task<ApiResult> InvalidateCache(RouteContext ctx)
    {
        InvalidateExpansionCache();
        return await Task.FromResult(new ApiResult(200, new { message = "Recipe template cache invalidated and rebuilt." }));
    }

    /// <summary>
    /// Get available material categories and job system item types (for UI dropdowns).
    /// GET /api/worldengine/recipe-templates/enums
    /// </summary>
    [HttpGet("/api/worldengine/recipe-templates/enums")]
    public static async Task<ApiResult> GetEnums(RouteContext ctx)
    {
        var materialCategories = Enum.GetValues<MaterialCategory>()
            .Where(c => c != MaterialCategory.None)
            .Select(c => new { value = c.ToString(), label = c.ToString() });

        var itemForms = Enum.GetValues<JobSystemItemType>()
            .Where(t => t != JobSystemItemType.None)
            .Select(t => new { value = t.ToString(), label = t.ToString() });

        return await Task.FromResult(new ApiResult(200, new
        {
            materialCategories,
            itemForms
        }));
    }

    // ==================== Helpers ====================

    private static IRecipeTemplateRepository ResolveRepository()
    {
        return AnvilCore.GetService<IRecipeTemplateRepository>()
               ?? throw new InvalidOperationException("IRecipeTemplateRepository service not available");
    }

    private static RecipeTemplateExpander ResolveExpander()
    {
        return AnvilCore.GetService<RecipeTemplateExpander>()
               ?? throw new InvalidOperationException("RecipeTemplateExpander service not available");
    }

    private static void InvalidateExpansionCache()
    {
        try
        {
            ResolveExpander().Invalidate();
        }
        catch
        {
            // Template expander may not be initialized yet during startup — silently ignore
        }
    }

    private static string? ValidateDto(RecipeTemplateDto dto)
    {
        if (string.IsNullOrWhiteSpace(dto.Tag)) return "Tag is required";
        if (string.IsNullOrWhiteSpace(dto.Name)) return "Name is required";
        if (string.IsNullOrWhiteSpace(dto.IndustryTag)) return "IndustryTag is required";
        if (dto.Ingredients == null || dto.Ingredients.Length == 0) return "At least one ingredient is required";
        if (dto.Products == null || dto.Products.Length == 0) return "At least one product is required";
        return null;
    }

    private static object ToDto(RecipeTemplate t)
    {
        return new
        {
            t.Tag,
            t.Name,
            t.Description,
            IndustryTag = t.IndustryTag.Value,
            t.RequiredKnowledge,
            Ingredients = t.Ingredients.Select(i => new
            {
                RequiredCategory = i.RequiredCategory.ToString(),
                RequiredForm = i.RequiredForm.ToString(),
                Quantity = i.Quantity.Value,
                i.MinQuality,
                i.IsConsumed,
                i.SlotIndex
            }).ToArray(),
            Products = t.Products.Select(p => new
            {
                OutputForm = p.OutputForm.ToString(),
                p.MaterialSourceSlot,
                Quantity = p.Quantity.Value,
                p.SuccessChance
            }).ToArray(),
            t.CraftingTimeRounds,
            t.KnowledgePointsAwarded,
            RequiredWorkstation = t.RequiredWorkstation?.Value,
            t.RequiredTools
        };
    }

    private static RecipeTemplate FromDto(RecipeTemplateDto dto)
    {
        return new RecipeTemplate
        {
            Tag = dto.Tag,
            Name = dto.Name,
            Description = dto.Description,
            IndustryTag = new IndustryTag(dto.IndustryTag),
            RequiredKnowledge = dto.RequiredKnowledge?.ToList() ?? [],
            Ingredients = dto.Ingredients?.Select(i =>
            {
                Enum.TryParse<MaterialCategory>(i.RequiredCategory, true, out MaterialCategory category);
                Enum.TryParse<JobSystemItemType>(i.RequiredForm, true, out JobSystemItemType form);
                return new TemplateIngredient
                {
                    RequiredCategory = category,
                    RequiredForm = form,
                    Quantity = Quantity.Parse(i.Quantity),
                    MinQuality = i.MinQuality,
                    IsConsumed = i.IsConsumed,
                    SlotIndex = i.SlotIndex
                };
            }).ToList() ?? [],
            Products = dto.Products?.Select(p =>
            {
                Enum.TryParse<JobSystemItemType>(p.OutputForm, true, out JobSystemItemType form);
                return new TemplateProduct
                {
                    OutputForm = form,
                    MaterialSourceSlot = p.MaterialSourceSlot,
                    Quantity = Quantity.Parse(p.Quantity),
                    SuccessChance = p.SuccessChance
                };
            }).ToList() ?? [],
            CraftingTimeRounds = dto.CraftingTimeRounds,
            KnowledgePointsAwarded = dto.KnowledgePointsAwarded,
            RequiredWorkstation = !string.IsNullOrEmpty(dto.RequiredWorkstation)
                ? new WorkstationTag(dto.RequiredWorkstation)
                : null,
            RequiredTools = dto.RequiredTools ?? [],
            Metadata = new Dictionary<string, object>()
        };
    }

    // ==================== DTO classes for request/response ====================

    private record RecipeTemplateDto
    {
        public string Tag { get; init; } = string.Empty;
        public string Name { get; init; } = string.Empty;
        public string? Description { get; init; }
        public string IndustryTag { get; init; } = string.Empty;
        public List<string>? RequiredKnowledge { get; init; }
        public TemplateIngredientDto[]? Ingredients { get; init; }
        public TemplateProductDto[]? Products { get; init; }
        public int? CraftingTimeRounds { get; init; }
        public int KnowledgePointsAwarded { get; init; }
        public string? RequiredWorkstation { get; init; }
        public List<string>? RequiredTools { get; init; }
    }

    private record TemplateIngredientDto
    {
        public string? RequiredCategory { get; init; }
        public string? RequiredForm { get; init; }
        public int Quantity { get; init; }
        public int? MinQuality { get; init; }
        public bool IsConsumed { get; init; } = true;
        public int SlotIndex { get; init; }
    }

    private record TemplateProductDto
    {
        public string? OutputForm { get; init; }
        public int MaterialSourceSlot { get; init; }
        public int Quantity { get; init; }
        public float? SuccessChance { get; init; }
    }
}
